blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView, \
    BlogManagementListView

app_name = 'blog'

urlpatterns = [
    path('create/', BlogCreateView.as_view(template_name='blog_form.html'), name='create'),
    path('', cache_page(60)(BlogListView.as_view(template_name='blog_list.html')), name='list'),
    path('blog_management/', BlogManagementListView.as_view(template_name='blog/blog_management.html'), name='content'),
    path('view/<int:pk>/', cache_page(60)(BlogDetailView.as_view(template_name='blog/blog_detail.html')), name='view'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(template_name='blog/blog_form.html'), name='edit'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(template_name='blog/blog_confirm_delete.html'), name='delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include(("newsletter.urls", 'newsletter'), namespace='newsletter')),
    path("users/", include(("users.urls", 'users'), namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
]

newsletter/urls.py
from django.urls import path
from newsletter.views import ClientsListCreateView, mailing_panel, MailingCreateView, mailings_manage, MailingListView, \
    MailingDetailView, toggle_block_status, BlogListView, PartnerListView, PartnersDetailView

app_name = 'mailing'

urlpatterns = [
    path('', BlogListView.as_view(), name='main'),
    path('client_list_create/', ClientsListCreateView.as_view(), name='client_list_create'),
    path('mailing_management/', mailing_panel, name='mailing_panel'),
    path('mailing_form/', MailingCreateView.as_view(), name='mailing_form'),
    path('manage_mailing/', mailings_manage, name='mailings_manage'),
    path('mailings_list_manage/', MailingListView.as_view(), name='mailings_list_manage'),
    path('mailing_detail_manage/<int:pk>/', MailingDetailView.as_view(), name='mailing_detail_manage'),
    path('toggle_block_status/<int:mailing_id>/', toggle_block_status, name='toggle_block_status'),
    path('partners_list_manage/', PartnerListView.as_view(), name='partners_list_manage'),
    path('partners_detail_manage/<int:pk>/', PartnersDetailView.as_view(), name='partners_detail_manage'),
]

users/urls.py
from django.urls import path

from django.contrib.auth.views import LoginView, LogoutView

from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, activate, email_activate, restore_password, VerifyEmailView

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('register/', RegisterView.as_view(template_name='users/register.html'), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('activate/<str:uid>/', activate, name="activate"),
    path('email_activated/', email_activate, name="email_activated"),
    path('restore_password/', restore_password, name="restore_password"),
    path('verify_email/<int:pk>/', VerifyEmailView.as_view(), name='verify_email'),
]

newsletter/models.py
from django.db import models

from config.settings import TIME_CHOICES
from users.models import User, NULLABLE


class Client(models.Model):
    """
    Модель для создания клиента
    """
    name = models.CharField(max_length=50, verbose_name='имя')
    surname = models.CharField(max_length=50, verbose_name='фамилия')
    email = models.EmailField(unique=True, verbose_name='почта')

    def __str__(self):
        return f'{self.name} {self.surname}'

    class Meta:
        verbose_name = 'клиент'
        verbose_name_plural = 'клиенты'
        ordering = ('name',)


class ClientsList(models.Model):
    """
    Модель для создания списка клиентов для рассылки
    """

    partner = models.ForeignKey(User, on_delete=models.CASCADE)
    clients = models.ManyToManyField(Client, verbose_name='клиент для списка')
    name = models.CharField(max_length=100, verbose_name='название списка')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'список клиентов для рассылки'
        verbose_name_plural = 'список клиентов для рассылки'
        ordering = ('name',)


class Mailing(models.Model):
    """
    Модель для настройки рассылки
    """
    partner = models.ForeignKey(User, on_delete=models.CASCADE)
    clients_list = models.ManyToManyField(ClientsList, verbose_name='список клиентов для рассылки')
    date = models.DateTimeField(auto_now=True, editable=False, verbose_name='дата создания')
    periodicity = models.CharField(max_length=50, verbose_name='периодичность', choices=TIME_CHOICES)
    status = models.CharField(max_length=50, default='создана', verbose_name='статус')
    name_mailing = models.CharField(max_length=50, verbose_name='название рассылки', **NULLABLE)
    is_active = models.BooleanField(default=True, verbose_name='блокировка рассылки')

    def __str__(self):
        return f'{self.name_mailing}'

    class Meta:
        verbose_name = 'рассылка'
        verbose_name_plural = 'рассылка'
        ordering = ('name_mailing',)
        permissions = [
            (
                'can_blocked',
                'can_blocked'
            )
        ]


class Message(models.Model):
    """
    Модель для сообщения
    """
    mailing = models.OneToOneField(Mailing, on_delete=models.CASCADE)
    theme = models.CharField(max_length=100, verbose_name='тема сообщения для рассылки')
    text = models.TextField(verbose_name='текст сообщения для рассылки')


class LogMailing(models.Model):
    """
    Модель для логов рассылки
    """
    mailing = models.ForeignKey(Mailing, on_delete=models.CASCADE)
    last_date = models.DateTimeField(auto_now=True, editable=False, verbose_name='дата последней попытки')
    status = models.CharField(max_length=20, verbose_name='статус попытки')
    server_response = models.CharField(max_length=200, verbose_name='ответ почтового сервера', **NULLABLE)

newsletter/forms.py
from django import forms
from newsletter.models import Client, ClientsList, Mailing, Message
from users.models import User


class PartnerForm(forms.ModelForm):
    """
    Форма для валидации и стилизации партнера
    """

    class Meta:
        model = User
        fields = ['phone', 'email']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ClientForm(forms.ModelForm):
    """
    Форма для валидации и стилизации клиента
    """

    class Meta:
        model = Client
        fields = ['name', 'surname', 'email']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ClientsListForm(forms.ModelForm):
    """
    Форма для списка клиентов для партнера
    """

    class Meta:
        model = ClientsList
        fields = ['name', 'clients']

    # форма для добавления клиента в список
    clients = forms.ModelMultipleChoiceField(
        queryset=Client.objects.all(),
        widget=forms.CheckboxSelectMultiple
    )


class MailingForm(forms.ModelForm):
    """
    Форма для рассылки
    """

    class Meta:
        model = Mailing
        fields = ['name_mailing', 'clients_list', 'periodicity']

    # форма для добавления списка клиентов
    clients_list = forms.ModelMultipleChoiceField(
        queryset=ClientsList.objects.all(),
        widget=forms.CheckboxSelectMultiple
    )


class MessageForm(forms.ModelForm):
    """
    Форма для сообщения
    """

    class Meta:
        model = Message
        fields = ['theme', 'text']

newsletter/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, DetailView, DeleteView, UpdateView
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required

from blog.forms import BlogForm
from blog.models import Blog
from newsletter.forms import ClientsListForm, MailingForm, MessageForm, PartnerForm
from newsletter.models import ClientsList, Mailing, LogMailing, Client
from users.models import User


class PartnerCreateView(LoginRequiredMixin, CreateView):
    """
    Класс для создания блоговой записи
    """
    model = User
    form_class = PartnerForm
    template_name = 'newsletter/partner_registration.html'
    success_url = reverse_lazy('newsletter:index')

    def form_valid(self, form):
        # Устанавливаем пользователя и partner_id перед сохранением Partner
        form.instance.user = self.request.user
        form.instance.partner_id = self.request.user.id
        return super().form_valid(form)


class ClientsListCreateView(LoginRequiredMixin, CreateView):
    """
    Контроллер для создания списка клиентов
    """
    model = ClientsList
    form_class = ClientsListForm
    template_name = 'newsletter/client_list_create.html'
    success_url = reverse_lazy('newsletter:mailing_panel')

    def form_valid(self, form):
        partner = self.request.user
        form.instance.partner = partner
        response = super().form_valid(form)
        return response


class MailingCreateView(LoginRequiredMixin, CreateView):
    """
    Контроллер для создания рассылки и сообщения
    """
    model = Mailing
    form_class = MailingForm
    template_name = 'newsletter/mailing_form.html'
    success_url = reverse_lazy('newsletter:mailing_panel')

    def form_valid(self, form):
        partner = self.request.user
        form.instance.partner = partner
        response = super().form_valid(form)

        message_form = MessageForm(self.request.POST)
        if message_form.is_valid():
            message = message_form.save(commit=False)
            message.mailing = self.object
            message.save()

        return response

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['message_form'] = MessageForm()
        return context


def mailing_panel(request):
    """
   Вывод страницы с управлением рассылкой
    """
    return render(request, 'newsletter/mailing_management.html')


def mailings_manage(request):
    """
   Вывод страницы с управлением рассылкой
    """
    return render(request, 'newsletter/manage_mailing.html')


class PartnerListView(LoginRequiredMixin, ListView):
    """
    Контроллер для создания списка пользователей сервиса
    """
    model = User
    form_class = PartnerForm
    template_name = 'newsletter/partners_list_manage.html'


class MailingListView(LoginRequiredMixin, ListView):
    """
    Контроллер для создания списка рассылок для менеджера
    """
    model = Mailing
    form_class = MailingForm
    template_name = 'newsletter/mailings_list_manage.html'


class MailingDetailView(LoginRequiredMixin, DetailView):
    """
    Контроллер для просмотра рассылки для менеджера
    """
    model = Mailing
    form_class = MailingForm
    template_name = 'newsletter/mailing_detail_manage.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['message'] = self.object.message
        return context


@login_required
def toggle_block_status(request, mailing_id):
    """
   Функция для переключения статуса активности рассылки
    """
    mailing = get_object_or_404(Mailing, id=mailing_id)

    # Переключаем статус блокировки
    if request.user.has_perm('mailing.can_blocked'):
        mailing.is_active = not mailing.is_active
        mailing.save()
        return redirect('newsletter:mailings_list_manage')
    else:
        # Обработка случая, когда у пользователя нет нужных прав
        return render(request, 'main/403.html')


@login_required
def toggle_block_partners(request, user_id):
    """
   Функция для переключения статуса активности у партнера
    """
    partners = get_object_or_404(User, id=user_id)

    # Переключаем статус блокировки
    if request.user.has_perm('mailing.can_blocked'):
        partners.is_active = not partners.is_active
        partners.save()
        return redirect('newsletter:partners_list_manage')
    else:
        # Обработка случая, когда у пользователя нет нужных прав
        return render(request, 'main/403.html')


def custom_permission_denied(request, exception):
    """
    При ошибке перевод на собственную страницу
    """
    return render(request, 'main/403.html', status=403)


class MailingPartnersListView(LoginRequiredMixin, ListView):
    """
     Класс для создания списка рассылок для менеджера
     """
    model = Mailing
    form_class = MailingForm
    template_name = 'newsletter/mailings_list_user.html'

    def get_queryset(self):
        # Фильтрация рассылок по текущему пользователю
        return Mailing.objects.filter(partner__partner=self.request.user)


class MailingPartnersDetailView(LoginRequiredMixin, DetailView):
    """
    Класс для просмотра рассылки для менеджера
    """
    model = Mailing
    form_class = MailingForm
    template_name = 'mailing/mailing_detail_user.html'

    def get_queryset(self):
        # Фильтрация рассылок по текущему пользователю
        return Mailing.objects.filter(partner__partner=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['message'] = self.object.message

        # Получение статистики из логов рассылки
        logs_fail = LogMailing.objects.filter(mailing=self.object).filter(status='неудачно')
        logs_good = LogMailing.objects.filter(mailing=self.object).filter(status='успешно').count
        context['logs_fail'] = logs_fail
        context['logs_good'] = logs_good
        return context


class MailingPartnersUpdateView(LoginRequiredMixin, UpdateView):
    """
    Класс для просмотра рассылки для менеджера
    """
    model = Mailing
    form_class = MailingForm
    template_name = 'mailing/mailing_update_user.html'
    success_url = reverse_lazy('mailing:mailings_list_user')


class MailingPartnersDeleteView(LoginRequiredMixin, DeleteView):
    """
    Контроллер для показа рассылок партнеру
    """

    model = Mailing
    success_url = reverse_lazy('newsletter:mailings_list_user')
    template_name = 'newsletter/mailing_confirm_delete.html'


class PartnersDetailView(LoginRequiredMixin, DetailView):
    """
    Класс для просмотра рассылки для менеджера
    """
    model = User
    form_class = PartnerForm
    template_name = 'newsletter/partners_detail_manage.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class BlogListView(ListView):
    """
    Класс для создания списка блоговых записей
    """
    model = Blog
    form_class = BlogForm
    template_name = 'newsletter/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Получите общее количество рассылок
        total_mailings = Mailing.objects.count()

        active_mailings = Mailing.objects.filter(is_active=True).count()

        total_clients = Client.objects.count()

        # Передайте информацию в контекст
        context['total_mailings'] = total_mailings
        context['active_mailings'] = active_mailings
        context['total_clients'] = total_clients

        return context

newsletter/templates/newsletter/basic_emplate.html
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" >
</head>
<body>
<svg xmlns="http://www.w3.org/2000/svg" class="d-none">
      <symbol id="check2" viewBox="0 0 16 16">
        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"></path>
      </symbol>
      <symbol id="circle-half" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"></path>
      </symbol>
      <symbol id="moon-stars-fill" viewBox="0 0 16 16">
        <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"></path>
        <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"></path>
      </symbol>
      <symbol id="sun-fill" viewBox="0 0 16 16">
        <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"></path>
      </symbol>
    </svg>
{% include 'newsletter/includes/inc_menu.html' %}


{% block content %}
{% endblock %}

 <footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
      <div class="col-12 col-md">
        <small class="d-block mb-3 text-body-secondary">&copy; 2017–2024</small>
      </div>
      <div class="col-6 col-md">
 <h5>О Компании</h5>
      <ul class="list-unstyled text-small">
        <li><a class="link-secondary text-decoration-none" href="#">Новости</a></li>
        <li><a class="link-secondary text-decoration-none" href="#">Вакансии</a></li>
        <li><a class="link-secondary text-decoration-none" href="#">Статьи</a></li>
        <li><a class="link-secondary text-decoration-none" href="#" target="_blank">Контакты</a></li>

      </ul>
    </div>
    <div class="col">
      <h5>Условия работы</h5>
      <ul class="list-unstyled text-small">
        <li><a class="link-secondary text-decoration-none" href="#">Оптовая продажа</a></li>
        <li><a class="link-secondary text-decoration-none" href="#">Розничная продажа</a></li>
      </ul>
      </div>
        <div class="col">
      <h5>Продажа</h5>
      <ul class="list-unstyled text-small">
        <li><a class="link-secondary text-decoration-none" href="#">Оптовая продажа</a></li>
        <li><a class="link-secondary text-decoration-none" href="#">Розничная продажа</a></li>
      </div>
     </div>
  </footer>
</div>
<script src="{% static 'js/bootstrap.bundle.min.js' %}" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

    </body>
</html>

newsletter/templates/newsletter/client_list_create.html
{% extends 'newsletter/basic_emplate.html'%}

{% block content %}

<div class="col-12">
  <div class="row">
    <div class="col-6">
      <div class="card">
        <div class="card-body">
          <form method="post">
              {% csrf_token %}
              {{ form.as_p }}
              <input type="submit" value="Сохранить">
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

newsletter/templates/newsletter/index.html
{% extends 'newsletter/basic_emplate.html' %}


{% block content %}


<div class="container">
  <div class="album py-5 bg-light">
    <div class="container">
      <div class="col-13">
        <div class="card">
          <div class="row">

          </div>
          {% if user.is_authenticated %}
              <a href="{% url 'blog:list' %}" class="btn btn-sm btn-outline-secondary text-center">Для подробной информации кликни сюда</a>
          {% else %}
              <a href="{% url 'users:login' %}" class="btn btn-sm btn-outline-secondary text-center">Авторизуйтесь, чтобы получить больше возможностей сайта</a>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</div>

{% if user.is_authenticated %}
    <div class="col-md-5">
        <div class="card mb-4 rounded-3 box-shadow">
            <ul class="list-group">

                <li class="list-group-item text-center">
                    <h5>СЕРВИС РАССЫЛОК</h5>
                </li>
                <li class="list-group-item text-center">
                    <h5>Ваши данные:</h5>

                    <p>{{ user.email }} </p>
                     {% if user.is_authenticated %}
            <a href="{% url 'newsletter:mailing_form' %}" class="icon-link btn btn-outline-success my-2">Создать запись</a>
                {% endif %}


                </li>

            </ul>
        </div>
    </div>

    <div class="col-md-5 offset-md-2">
        <div class="card mb-4 rounded-3 box-shadow">
            <div class="card-header py-3">
                <h5>Рекламный сервис:</h5>
                <p>Количество рассылок на данный момент: {{ total_mailings }}</p>
                <p>Наших уникальных клиентов для рассылки: {{ total_clients }}</p>
                <p>Количество активных рассылок: {{ active_mailings }}</p>
            </div>
            <div class="card-body">
            <li class="list-group-item text-center">
                <a href="#" class="btn text-center">Стать нашим партнером</a>
            </li>
            </div>
        </div>
    </div>
{% endif %}

{% endblock %}

newsletter/templates/newsletter/mailing_confirm_delete.html
{% extends 'newsletter/basic_emplate.html' %}

{% block content %}

<div class="col-12">
  <div class="row">
    <div class="col-6">
      <div class="card">
        <div class="card-body">
          <form method="post">
            {% csrf_token %}
            <p> Хотите удалить рассылку "{{ object.name_mailing }}"?</p>
            <button type="submit" class="btn btn-danger">Подтвердить</button>
            <a href="{% url 'mailing:mailings_list_user' %}" class="btn btn-warning">Отмена</a>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

newsletter/templates/newsletter/mailing_detail_manage.html
{% extends 'newsletter/basic_emplate.html' %}


{% block content %}

<div class="container">
    <div class="col-md-4">
        <div class="card mb-4 box-shadow">
            <div class="card-body">
                <h3 class="card-title">{{ object.title }}</h3>
                <small class="text-body-secondary">Дата публикации: {{ object.date|date:'d-m-Y H:i:s' }}</small><br><br>
                 <h4>Сообщение рассылки:</h4>
                <p>{{ object.message.theme }}: {{ object.message.text }}</p>
                <!-- Форма для блокировки/разблокировки -->
                 <form method="post" action="{% url 'mailing:toggle_block_status' object.id %}">
                    {% csrf_token %}
                    <button type="submit">
                        {% if object.is_active %}
                            Заблокировать
                        {% else %}
                            Разблокировать
                        {% endif %}
                    </button>
                </form>

            </div>
        </div>
</div>

{% endblock %}

newsletter/templates/newsletter/mailing_form.html
{% extends 'newsletter/basic_emplate.html' %}

{% block content %}

<div class="col-12">
  <div class="row">
    <div class="col-6">
      <div class="card">
        <div class="card-body">
          <form method="post">
              {% csrf_token %}
              {{ form.as_p }}
              {{ message_form.as_p }}
              <input type="submit" value="создать">
          </form>
        </div>
      </div>
    </div>
  </div>
</div>




{% endblock %}

newsletter/templates/newsletter/mailing_management.html
{% extends 'newsletter/basic_emplate.html' %}

{% block content %}

<div class="col-12">
  <form class="row" method="post" enctype="multipart/form-data">
    <div class="col-3"></div>
    <div class="col-6">
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">
            Управление рассылками

              {% if user.is_active == True %}
                <li><a href="{% url 'newsletter:client_list_create' %}" class="text">Создать свой список клиентов</a></li>
                <li><a href="{% url 'newsletter:mailing_form' %}" class="text">Создать рассылку</a></li>
                <li><a href="{% url 'newsletter:mailings_list_manage' %}" class="text">Просмотреть свои рассылки</a></li>
              {% endif %}


          </h3>
      </div>
    </div>
  </form>
</div>


{% endblock %}

newsletter/templates/newsletter/mailings_list_manage.html
{% extends 'newsletter/basic_emplate.html' %}
{% load my_tags %}

{% block content %}

<div class="col-12 mb-5">
</div>
<div class="container">
  <div class="album py-5 bg-light">
    <div class="container">
      <div class="row">
        {% for object in object_list %}
          <div class="col-md-4">
            <div class="card mb-4 box-shadow">
              <div class="card-body">
                <p class="card-text">
                  Наименование рассылки: {{ object.name_mailing }}
                </p>
                <p class="card-text">
                  Статус отправки: {{ object.status }}
                </p>
                {% if object.is_active is True %}
                  <p class="card-text">
                      Статус блокировки: рассылка не заблокирована
                  </p>
                {% else %}
                  <p class="card-text">
                      Статус блокировки: рассылка заблокирована
                  </p>
                {% endif %}
                 <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <a href="{% url 'newsletter:mailing_detail_manage' object.pk %}"
                          class="btn btn-sm btn-outline-secondary">Подробнее</a>
                      </div>
                  </div>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
  </div>
</div>

{% endblock %}

newsletter/templates/newsletter/partners_list_manage.html
{% extends 'newsletter/basic_emplate.html' %}
{% load my_tags %}

{% block content %}

<div class="col-12 mb-5">
</div>
<div class="container">
  <div class="album py-5 bg-light">
    <div class="container">
      <div class="row">
        {% for object in object_list %}
          <div class="col-md-4">
            <div class="card mb-4 box-shadow">
              <div class="card-body">
                <p class="card-text">
                  Наименование компании: {{ object.email }}
                </p>
                {% if object.is_active is True %}
                  <p class="card-text">
                      Статус блокировки: компания не заблокирована
                  </p>
                {% else %}
                  <p class="card-text">
                      Статус блокировки: компания заблокирована
                  </p>
                {% endif %}
                 <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <a href="{% url 'newsletter:partners_detail_manage' object.pk %}"
                          class="btn btn-sm btn-outline-secondary">Подробнее</a>
                      </div>
                  </div>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
  </div>
</div>



{% endblock %}