blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView, \
    BlogManagementListView

app_name = 'blog'

urlpatterns = [
    path('create/', BlogCreateView.as_view(template_name='blog_form.html'), name='create'),
    path('', cache_page(60)(BlogListView.as_view(template_name='blog_list.html')), name='list'),
    path('blog_management/', BlogManagementListView.as_view(template_name='blog/blog_management.html'), name='content'),
    path('view/<int:pk>/', cache_page(60)(BlogDetailView.as_view(template_name='blog/blog_detail.html')), name='view'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(template_name='blog/blog_form.html'), name='edit'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(template_name='blog/blog_confirm_delete.html'), name='delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include(("newsletter.urls", 'newsletter'), namespace='newsletter')),
    path("users/", include(("users.urls", 'users'), namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
]

users/urls.py
from django.urls import path

from django.contrib.auth.views import LoginView, LogoutView

from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, activate, email_activate, restore_password, VerifyEmailView

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('register/', RegisterView.as_view(template_name='users/register.html'), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('activate/<str:uid>/', activate, name="activate"),
    path('email_activated/', email_activate, name="email_activated"),
    path('restore_password/', restore_password, name="restore_password"),
    path('verify_email/<int:pk>/', VerifyEmailView.as_view(), name='verify_email'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

NULLABLE = {"blank": True, "null": True}


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='Email')

    image_ph = models.ImageField(
        upload_to="users/avatars/", **NULLABLE, verbose_name="Аватар"
    )
    phone = models.CharField(max_length=35, **NULLABLE, verbose_name='Телефон')
    country = models.CharField(max_length=35, **NULLABLE, verbose_name='Страна')
    verification_code = models.CharField(max_length=50, verbose_name='код верификации email', **NULLABLE)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email

    class Meta:
        verbose_name = "пользователь"
        verbose_name_plural = "пользователи"

users/forms.py
from django import forms

from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from users.models import User


class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class UserProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('email', 'phone', 'country', 'image_ph')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['password'].widget = forms.HiddenInput()


class VerificationCodeForm(forms.Form):
    verification_code = forms.CharField(max_length=6, label='Код верификации')

users/views.py
from django.conf import settings
from django.core.mail import send_mail
from django.shortcuts import redirect, get_object_or_404, render
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView
from users.forms import UserRegisterForm, UserProfileForm, VerificationCodeForm

from users.models import User
from django.contrib.auth import login

from django.urls import reverse_lazy
from django.views import View

from utils import generate_password


class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'users/register.html'

    def form_valid(self, form):
        new_user = form.save(commit=False)
        # Пользователь не активен до верификации
        new_user.is_active = False
        # получение кода для почты
        verification_code = generate_password()
        # сохранение кода в поле юзера
        new_user.verification_code = verification_code
        new_user.save()

        # Отправка кода верификации на почту
        send_mail(
            subject='Проверка почты',
            message=f'Ваш код верификации: {verification_code}',
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[new_user.email]
        )

        # Перенаправление пользователя на страницу ввода кода верификации
        return redirect('users:verify_email', pk=new_user.pk)


class VerifyEmailView(View):
    """
    Верификация почты
    """
    template_name = 'users/verify_email.html'

    def get(self, request, pk):
        user = get_object_or_404(User, pk=pk)
        form = VerificationCodeForm()
        return render(request, self.template_name, {'form': form, 'user': user})

    def post(self, request, pk):
        user = get_object_or_404(User, pk=pk)
        form = VerificationCodeForm(request.POST)
        # проверка кода
        if form.is_valid() and user.verification_code == form.cleaned_data['verification_code']:
            # юзер становится активным
            user.is_active = True
            user.save()
            login(request, user)
            return redirect('users:email_activated')
        return render(request, self.template_name, {'form': form, 'user': user})


class ProfileView(UpdateView):
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy('main:main')

    def get_object(self, queryset=None):
        return self.request.user


def email_activate(request):
    """
    Контроллер для страницы, которая выводит информацию юзеру об успешности
    верификации почты
    """
    return render(request, "users/email_activate.html")


def activate(request, uid):
    """
    Контроллер для активации пользователя при восстановлении пароля
    """
    user = User.objects.filter(email_verify=int(uid)).first()
    user.is_active = True
    user.save()
    return redirect(reverse('main:main'))


def restore_password(request):
    """
    Контроллер для верификации пароля
    """
    if request.method == "POST":
        email = request.POST.get('email')
        user = get_object_or_404(User, email=email)
        new_password = generate_password()
        send_mail(
            subject='Восстановление пароля',
            message=f'Ваш новый пароль: {new_password}',
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[user.email]
        )
        user.set_password(new_password)
        user.save()
        return redirect(reverse('users:login'))
    return render(request, "users/restore_password.html")

users/templates/users/email_activated.html
{% extends 'newsletter/basic_emplate.html' %}
{% block content%}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-5">Почта подтверждена, приятного пользования нашим сайтом.</h1>
    <p class="lead">С уважением, Ваша команда "SKYLOVE"</p>
    <li><a href="{% url 'main:main' %}" class="text-white">Перейти на главную страницу</a></li>
</div>
{% endblock %}

users/templates/users/login.html
{% extends 'newsletter/basic_emplate.html' %}

{% block content %}

<div class="col-12">
  <form class="row" method="post" enctype="multipart/form-data">
    <div class="col-3"></div>
    <div class="col-6">
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">
            Вход
          </h3>
        </div>
        <div class="card-body">
          {% csrf_token %}
          {{ form.as_p }}
          <button type="submit" class="btn btn-success">Войти</button>
          <a class="p-1.5 btn btn-outline-primary" href="{% url 'users:restore_password' %}">Восстановить пароль</a>
          <a class="p-1.5 btn btn-outline-primary" href="{% url 'users:register' %}">Зарегистрироваться</a>
        </div>
        <div class="card-footer"></div>
      </div>
    </div>
  </form>
</div>


{% endblock %}

users/templates/users/register.html
{% extends 'newsletter/basic_emplate.html' %}

{% block content %}

<div class="col-12">
  <form class="row" method="post" enctype="multipart/form-data">
    <div class="col-3"></div>
    <div class="col-6">
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">
            Регистрация
          </h3>
        </div>
        <div class="card-body">
          {% csrf_token %}
          {{ form.as_p }}
          <button type="submit" class="btn btn-success">Регистрация</button>

        </div>
        <div class="card-footer"></div>
      </div>
    </div>
  </form>
</div>


{% endblock %}

users/templates/users/restore_password.html
{% extends 'newsletter/basic_emplate.html' %}
{% block content%}

<div class="container text-center">
    <div class="col-md-6 text-center">
        <div class="card mb-2 box-shadow">
            <div class="card-header">
                <h4><font color= 'green'> Восстановление пароля<font></h4>
            </div>
            <div class="card-body">
                <p class="card-text">
                <h5><font color= 'blue'>Укажите ваш email<font></h5>
                <form method="post">
                    {% csrf_token %}
                    <input class="form-control mb-2" name="email"/>
                    <button type="submit" class=" mb-1.5 btn btn-primary form-control">Восстановить пароль</button>
                </form>
                </p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'newsletter/basic_emplate.html' %}

{% block content %}

<div class="col-12">
  <form class="row" method="post" enctype="multipart/form-data">
    <div class="col-3"></div>
    <div class="col-6">
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">
            Профиль
          </h3>
        </div>
        <div class="card-body">
          {% csrf_token %}
          {{ form.as_p }}
          <button type="submit" class="btn btn-success">Сохранить</button>

        </div>
        <div class="card-footer"></div>
      </div>
    </div>
  </form>
</div>


{% endblock %}

users/templates/users/verify_email.html
{% extends 'newsletter/basic_emplate.html' %}

{% block content %}
  <h2>Введите код</h2>
  <form method="post" action="">
    <h2>Введите код верификации</h2>
    <form method="post" action="{% url 'users:verify_email' pk=user.pk %}">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" ">Подтвердить</button>
    </form>
{% endblock %}